package idare.imagenode.internal.DataManagement;

/**
 * Generate IDs for DataSets, in order that sets have distinct IDs.
 * @author Thomas Pfau
 *
 */
public class DataSetIDProvider {

	int currentID;
	/**
	 * Initialize a new DataSetIDProvider
	 */
	public DataSetIDProvider() {
		// TODO Auto-generated constructor stub
		currentID= 0;
	}
	/**
	 * Get the next ID.
	 * @return the next integer generated by this Provider
	 */
	public int getNextID()
	{
		currentID+=1;
		int returnvalue = new Integer(currentID);		
		return returnvalue;
	}
	
	/**
	 * Reset the IDs, with the provided id being the highest ID already used.
	 * @param newID
	 */
	public void reset(int newID)
	{
		currentID = newID;
		
	}
}
